project_name: ekstrap
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  hooks:
    post: upx --brute ./dist/linux_amd64/ekstrap
archive:
  replacements:
    amd64: x86_64
  format: binary
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
nfpm:
  vendor: Edward Robinson
  homepage: https://github.com/errm/ekstrap/
  maintainer: Edward Robinson <edward-robinson@cookpad.com>
  name_template: '{{ .ProjectName }}'
  description:  Bootstrap for EKS
  license: Apache 2.0
  formats:
  - deb
  - rpm
  dependencies:
  - dbus
  - systemd
  bindir: /usr/sbin
  files:
    "systemd/": "/etc/systemd/system"
  scripts:
    postinstall: "scripts/postinstall.sh"
  overrides:
    rpm:
      replacements:
        amd64: x86_64
dockers:
- image: errm/ekstrap
  dockerfile: Dockerfile
  tag_templates:
  - "{{ .Major }}"
  - "{{ .Major }}.{{ .Minor }}"
  - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - latest

sign:
  artifacts: checksum
