language: go

go:
  - "1.10.x"

services:
  - docker

before_script: bash .travis/setup.sh

script: make

deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/release.sh
  on:
    tags: true
