language: go

go:
  - "1.11.x"

services:
  - docker

before_script: bash .travis/setup.sh

script: make test ekstrap

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/release.sh
  on:
    tags: true
