language: go

go:
  - "1.10.x"

services:
  - docker

before_script:
  - make install-linter

script:
  - make all lint

deploy:
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      tags: true
