language: go

go:
  - "1.10.x"

addons:
  apt:
    packages:
    - rpm

services:
  - docker

before_script:
  - make install-linter

script:
  - make all lint

after_success:
- test -n "$TRAVIS_TAG" && docker login -u=errm -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
