language: go

go:
  - "1.10.x"

services:
  - docker

before_script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - make all lint

deploy:
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      tags: true
