FROM golang:1.10-alpine3.7

ARG GORELEASER_VERSION

RUN apk add --no-cache \
        curl \
        git \
    && curl -L \
        https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz \
    | tar -xzf - -C /usr/local/bin/

WORKDIR $GOPATH/src/github.com/errm/ekstrap

ENTRYPOINT [ "/usr/local/bin/goreleaser" ]
